variant: fcos
version: 1.5.0
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: "${HOST_NAME}.${DOMAIN_NAME}"
passwd:
  users:
    - name: root
      ssh_authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXU66AnXlGnT6EihSomvIjmA584LpjWzMVFDKfMCij8 anatolii@MiWiFi-RB01-srv"
