variant: fcos
version: 1.5.0
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: "${HOST_NAME}.${DOMAIN_NAME}"
    - path: /etc/haproxy/haproxy.cfg
      mode: 0644
      contents:
        local: runtime/haproxy.cfg
    - path: /usr/local/bin/start.sh
      mode: 0755
      contents:
        local: config/nodes/loadbalancer/start.sh
systemd:
  units:
    - name: start.service
      enabled: true
      contents_local: config/nodes/start.service
passwd:
  users:
    - name: root
      ssh_authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXU66AnXlGnT6EihSomvIjmA584LpjWzMVFDKfMCij8 anatolii@MiWiFi-RB01-srv"
